"""
Utility modules for the Visual Localization (VisLoc) project.

This package provides utility functions and constants used throughout the project.
"""

from visloc.utils.constants import (
    DEFAULT_CONFIG_PATH,
    DEFAULT_ENV_VAR_NAME,
    DEFAULT_OUTPUT_PATH,
    DEFAULT_MAP_PATH,
    DEFAULT_QUERY_PATH,
    DEFAULT_RESIZE_SIZE,
    DEFAULT_NMS_RADIUS,
    DEFAULT_KEYPOINT_THRESHOLD,
    DEFAULT_MAX_KEYPOINTS,
    DEFAULT_SINKHORN_ITERATIONS,
    DEFAULT_MATCH_THRESHOLD,
    DEFAULT_WEIGHTS,
    DEFAULT_FOCAL_LENGTH,
    DEFAULT_RESOLUTION_HEIGHT,
    DEFAULT_RESOLUTION_WIDTH,
    DEFAULT_HFOV_DEG,
    DEFAULT_LOGGING_LEVEL,
    DEFAULT_LOGGING_FORMAT,
    DEFAULT_LOGGING_DATE_FORMAT,
    DEFAULT_DEVICE,
    CPU_DEVICE,
)

__all__ = [
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_ENV_VAR_NAME",
    "DEFAULT_OUTPUT_PATH",
    "DEFAULT_MAP_PATH",
    "DEFAULT_QUERY_PATH",
    "DEFAULT_RESIZE_SIZE",
    "DEFAULT_NMS_RADIUS",
    "DEFAULT_KEYPOINT_THRESHOLD",
    "DEFAULT_MAX_KEYPOINTS",
    "DEFAULT_SINKHORN_ITERATIONS",
    "DEFAULT_MATCH_THRESHOLD",
    "DEFAULT_WEIGHTS",
    "DEFAULT_FOCAL_LENGTH",
    "DEFAULT_RESOLUTION_HEIGHT",
    "DEFAULT_RESOLUTION_WIDTH",
    "DEFAULT_HFOV_DEG",
    "DEFAULT_LOGGING_LEVEL",
    "DEFAULT_LOGGING_FORMAT",
    "DEFAULT_LOGGING_DATE_FORMAT",
    "DEFAULT_DEVICE",
    "CPU_DEVICE",
]
